#
# Makefile for Samsung NRNx NFC driver
#

subdir-ccflags-y += -Werror -I$(srctree)/drivers/misc/mediatek/include
subdir-ccflags-y += -Werror -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include
subdir-ccflags-y += -Werror -I$(srctree)/drivers/misc/mediatek/include/mt-plat
subdir-ccflags-y += -Werror -I$(srctree)/drivers/misc/mediatek/pmic/include

obj-$(CONFIG_SEC_NFC)	    += sec_nfc.o

ccflags-$(CONFIG_NFC_DEBUG) := -DDEBUG

