#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_ELAN_EFSA680RC) += elan/
obj-$(CONFIG_ZET_ZFS1670A) += zet/
